"""
Inductive Rule Discovery QA (Task C, reference inductive gap, ).

Show 5-6 examples of an input->output mapping using text+image combos.
Ask for the rule or predict the next output.

Difficulty axes:
  A) Rule complexity (linear transform -> modular -> composite)
  B) Number of examples shown (3 -> 6)
  C) Output format (numeric -> symbolic)
"""
import math
import random
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from PIL import Image

from .standalone_base import StandaloneVisualEnv

class InductiveRuleDiscoveryQA(StandaloneVisualEnv):
    ENV_NAME = "inductive_rule_discovery"

    def _level_config(self, level: int) -> Dict:
        level = max(0, min(level, 9))
        return {
            "n_examples": 3 + level // 2,            # 3,3,4,4,5,5,6,6,7,7
            "rule_type": "linear" if level <= 2 else
                        "quadratic" if level <= 4 else
                        "modular" if level <= 6 else "composite",
            "show_function_hint": level <= 3,
        }

    def _generate_problem(
        self, seed: int, parameter: Dict
    ) -> Optional[Tuple[str, str, Image.Image]]:
        level = int(parameter.get("level", 0))
        level = max(0, min(level, 9))
        cfg = self._level_config(level)
        rng = random.Random((self.seed or 0) * 1000 + level * 37 + 991)
        self._primary_complexity_feature = cfg["n_examples"]

        n_ex = cfg["n_examples"]
        rule = cfg["rule_type"]
        # Hint label only matches the actual rule family (bugfix).
        rule_hint = {
            "linear": "linear rule",
            "quadratic": "quadratic rule",
            "modular": "modular (mod) rule",
            "composite": "composite rule (depends on parity)",
        }[rule]

        # Generate rule and examples — much more diversity now.
        if rule == "linear":
            a = rng.randint(2, 5)
            b = rng.randint(-3, 5)
            fn = lambda x: a * x + b
        elif rule == "quadratic":
            a = rng.choice([1, 2])
            b = rng.randint(-2, 2)
            sign = rng.choice([1, -1])
            fn = lambda x, _a=a, _b=b, _s=sign: _s * _a * x * x + _b
        elif rule == "modular":
            m = rng.choice([3, 4, 5, 6, 7])
            shift = rng.randint(0, 2)
            fn = lambda x, _m=m, _sh=shift: (x + _sh) % _m
        else:  # composite
            a = rng.randint(2, 4)
            b = rng.randint(1, 3)
            fn = lambda x, _a=a, _b=b: _a * x + _b if x % 2 == 0 else _a * x - _b

        # Generate input values and compute outputs.  Use a wider input pool
        # (random, non-consecutive) at higher levels to vary appearance.
        if level <= 3:
            input_pool = list(range(1, n_ex + 2))
        elif level <= 6:
            input_pool = rng.sample(range(1, 12), n_ex + 1)
        else:
            input_pool = rng.sample(range(1, 18), n_ex + 1)
        rng.shuffle(input_pool)
        shown_inputs = sorted(input_pool[:n_ex])
        test_input = input_pool[n_ex]

        examples = [(x, fn(x)) for x in shown_inputs]
        correct_output = fn(test_input)

        # Pick a layout flavour — vertical-list, horizontal table, or grid.
        layout = rng.choice(["list", "table", "grid"])

        # Render
        img = self._render_examples(examples, test_input, cfg, rng, rule_hint, layout)

        # Question text never includes n_examples or test_input value
        # (those go on the image, marked with "?").
        templates = [
            ("The image shows several input-output pairs following a hidden rule. "
             "Use the rule to predict the output for the highlighted test input "
             "(marked with '?'). Answer with a single integer."),
            ("Examine the input-output examples in the figure. They follow one "
             "hidden rule. What is the output for the test input shown with '?' "
             "in the figure? Answer with a single integer."),
            ("Several worked examples in the figure illustrate a hidden mapping "
             "f(x). Apply the same mapping to the highlighted test input "
             "(labeled with '?') and answer with a single integer."),
            ("Look at the example pairs (input -> output) in the image. Discover "
             "the rule, then output f(test_input) where test_input is the value "
             "marked '?' in the figure. Answer with a single integer."),
            ("Infer the pattern from the example pairs shown. Apply it to the "
             "test input marked with '?' and report f(test_input) as an integer."),
            ("The figure presents example (x, f(x)) pairs generated by a single "
             "hidden rule. Determine the rule and evaluate it at the highlighted "
             "'?' input. Integer answer only."),
            ("Each example in the figure obeys the same mapping. Work out the "
             "mapping and produce the output for the test input labeled '?'. "
             "Answer with a single integer."),
            ("From the worked examples in the image, identify the underlying "
             "function. Then compute its value at the input highlighted by '?'. "
             "Integer output required."),
            ("Study the (input, output) pairs in the diagram. They all follow "
             "one rule. Predict the missing output for the '?' entry and reply "
             "with one integer."),
            ("Based on the examples in the figure, find the hidden function and "
             "apply it to the test value marked '?'. Respond with a single integer."),
            ("The image illustrates a function via examples. Deduce the function "
             "and determine what it produces for the '?' input. Output a single integer."),
            ("Analyze the mapping shown by the (x -> f(x)) examples in the "
             "figure. Using the same mapping, return f at the '?' input as an integer."),
            ("Several worked-out values of a hidden rule appear in the figure. "
             "Recover the rule and apply it to the highlighted test input '?'. "
             "Give an integer answer."),
            ("In the image, each pair (x, f(x)) shares a common rule. Determine "
             "what f yields at the test input (the '?' entry). Integer only."),
            ("The image's examples encode a single mathematical rule. Use it to "
             "predict the output at the '?' marker. Report the integer."),
            ("Observe the input-output pattern displayed in the figure. Extend "
             "it to the test input labeled '?' and state the predicted integer output."),
        ]
        sidx = (self.seed or 0) % 16
        question = templates[sidx]
        answer = str(correct_output)

        return question, answer, img

    def _render_examples(self, examples, test_input, cfg, rng,
                          rule_hint="linear rule", layout="list"):
        style = self._random_style()
        sc = style["figsize_scale"]
        n = len(examples)
        # Extra visual knobs for image diversity.
        arrow_col = rng.choice(["#7f8c8d", "#566573", "#4a5568",
                                "#2c3e50", "#3b3b3b", "#6b6b6b"])
        accent_col = rng.choice(["#e74c3c", "#c0392b", "#d35400",
                                  "#d90429", "#b8364c", "#9c27b0"])
        test_bg = rng.choice(["#fff8dc", "#fdf6e3", "#fef9ef",
                               "#f7f3ea", "#fefae0", "#fff1e6"])
        output_bg = rng.choice(["#ecf0f1", "#e9edf2", "#eef2f7",
                                 "#f4f4f4", "#eaf0f6", "#e8ecef"])
        fs_scale = rng.uniform(0.94, 1.08)
        # Override bg_color and dpi with a seed-dependent choice to maximize
        # cross-seed image distinctness (style rng alone may collide).
        style["bg_color"] = rng.choice(["#ffffff", "#f8f9fa", "#fefefe",
                                         "#f5f5f5", "#fff8f0", "#fffdf7",
                                         "#fafbfc", "#fffbf2", "#f9fafb",
                                         "#fbfcfd"])
        style["dpi"] = rng.choice([100, 105, 110, 115, 120, 125])
        style["figsize_scale"] = rng.uniform(0.88, 1.18)
        sc = style["figsize_scale"]
        box_w = rng.uniform(1.3, 1.7)
        box_h = rng.uniform(0.45, 0.58)
        arrow_lw = rng.uniform(1.2, 1.9)
        box_lw = rng.uniform(0.8, 1.4)
        # Random decorative frame or banner for extra visual diversity.
        deco = rng.choice(["none", "frame", "top_band", "corner_mark", "underline"])
        deco_color = rng.choice(style["palette"]) if isinstance(style["palette"], list) else "#95a5a6"
        style["_extra"] = {"arrow": arrow_col, "accent": accent_col,
                            "test_bg": test_bg, "output_bg": output_bg,
                            "fs_scale": fs_scale, "box_w": box_w,
                            "box_h": box_h, "arrow_lw": arrow_lw,
                            "box_lw": box_lw, "deco": deco,
                            "deco_color": deco_color}

        title_pool = [
            "Input-Output Rule Discovery",
            "Hidden Rule Inference",
            "Pattern: input -> output",
            "Discover the Rule",
            "f(x) Examples",
            "Find the Hidden Mapping",
            "Inductive Reasoning Puzzle",
            "Predict the Next Output",
            "What is f(?)",
            "Rule Induction from Examples",
            "Input -> Output Pattern",
            "Infer the Function",
            "Learn the Rule, Predict Output",
            "Complete the Pattern",
            "From Examples to Rule",
            "Function Discovery Task",
        ]
        title = rng.choice(title_pool)

        if layout == "table":
            return self._render_table(examples, test_input, style, rng, title,
                                       cfg, rule_hint)
        if layout == "grid":
            return self._render_grid(examples, test_input, style, rng, title,
                                      cfg, rule_hint)
        # default: list
        fig_h = max(5, n * 0.8 + 3)
        fig = plt.figure(figsize=(8 * sc, fig_h * sc))
        fig.patch.set_facecolor(style["bg_color"])
        ax = fig.add_subplot(111)
        ax.set_xlim(0, 10)
        ax.set_ylim(0, fig_h)
        ax.axis("off")

        ax.text(5, fig_h - 0.3, title,
               fontsize=14, fontweight="bold", ha="center", va="top",
               family=style["font_family"])

        # Apply decorative flourish for cross-seed image distinctness.
        _ex = style.get("_extra", {})
        _deco = _ex.get("deco", "none")
        _dc = _ex.get("deco_color", "#95a5a6")
        if _deco == "frame":
            ax.add_patch(mpatches.Rectangle((0.15, 0.15), 9.7, fig_h - 0.3,
                                            fill=False, edgecolor=_dc,
                                            linewidth=1.5))
        elif _deco == "top_band":
            ax.add_patch(mpatches.Rectangle((0, fig_h - 0.9), 10, 0.25,
                                            facecolor=_dc, alpha=0.35,
                                            edgecolor="none"))
        elif _deco == "corner_mark":
            ax.add_patch(mpatches.Rectangle((0.1, fig_h - 0.5), 0.4, 0.4,
                                            facecolor=_dc, alpha=0.6,
                                            edgecolor="none"))
        elif _deco == "underline":
            ax.plot([3.0, 7.0], [fig_h - 0.75, fig_h - 0.75],
                    color=_dc, linewidth=2.0)

        y = fig_h - 1.2
        ax.text(0.5, y, "Examples:", fontsize=12, fontweight="bold",
               family=style["font_family"], color="#2c3e50")
        y -= 0.6

        # Optional reorder for visual variety.
        ex_order = list(examples)
        if rng.random() < 0.3:
            rng.shuffle(ex_order)

        ex = style.get("_extra", {})
        fs_s = ex.get("fs_scale", 1.0)
        for i, (x, fx) in enumerate(ex_order):
            box_color = style["palette"][i % len(style["palette"])]
            rect = mpatches.FancyBboxPatch((1.0, y - 0.25), ex.get("box_w", 1.5), ex.get("box_h", 0.5),
                                           boxstyle="round,pad=0.05",
                                           fc=box_color, ec="black", lw=1.0, alpha=0.8)
            ax.add_patch(rect)
            ax.text(1.75, y, str(x), fontsize=11 * fs_s, ha="center", va="center",
                   fontweight="bold", color="white")

            ax.annotate("", xy=(4.0, y), xytext=(3.0, y),
                       arrowprops=dict(arrowstyle="->",
                                       color=ex.get("arrow", "#7f8c8d"), lw=1.5))

            rect2 = mpatches.FancyBboxPatch((4.5, y - 0.25), ex.get("box_w", 1.5), ex.get("box_h", 0.5),
                                            boxstyle="round,pad=0.05",
                                            fc=ex.get("output_bg", "#ecf0f1"),
                                            ec="black", lw=1.0)
            ax.add_patch(rect2)
            ax.text(5.25, y, str(fx), fontsize=11 * fs_s, ha="center", va="center",
                   fontweight="bold", color="#2c3e50")
            y -= 0.7

        # Test input
        y -= 0.5
        ax.plot([0.5, 9.5], [y + 0.3, y + 0.3], color="#95a5a6", linewidth=1.0)
        y -= 0.2
        ax.text(0.5, y, "Predict:", fontsize=12, fontweight="bold",
               family=style["font_family"], color="#e74c3c")

        rect3 = mpatches.FancyBboxPatch((1.0, y - 0.55), 1.5, 0.5,
                                         boxstyle="round,pad=0.05",
                                         fc=ex.get("accent", "#e74c3c"),
                                         ec="black", lw=1.0, alpha=0.8)
        ax.add_patch(rect3)
        ax.text(1.75, y - 0.3, str(test_input), fontsize=11 * fs_s, ha="center", va="center",
               fontweight="bold", color="white")

        ax.annotate("", xy=(4.0, y - 0.3), xytext=(3.0, y - 0.3),
                   arrowprops=dict(arrowstyle="->",
                                   color=ex.get("arrow", "#7f8c8d"), lw=1.5))

        rect4 = mpatches.FancyBboxPatch((4.5, y - 0.55), 1.5, 0.5,
                                         boxstyle="round,pad=0.05",
                                         fc=ex.get("test_bg", "#dddddd"),
                                         ec=ex.get("accent", "#e74c3c"), lw=2.0,
                                         linestyle="--")
        ax.add_patch(rect4)
        ax.text(5.25, y - 0.3, "?", fontsize=14 * fs_s, ha="center", va="center",
               fontweight="bold", color=ex.get("accent", "#e74c3c"))

        if cfg.get("show_function_hint"):
            ax.text(7.5, y - 0.3, f"(hint: {rule_hint})", fontsize=8,
                   color="#95a5a6", ha="center")

        fig.tight_layout()
        return self.fig_to_pil(fig, dpi=style["dpi"])

    def _render_table(self, examples, test_input, style, rng, title, cfg, rule_hint):
        sc = style["figsize_scale"]
        ex = style.get("_extra", {})
        fs_s = ex.get("fs_scale", 1.0)
        n = len(examples)
        fig = plt.figure(figsize=(max(6.5, n * 1.2 + 2) * sc, 4.5 * sc))
        fig.patch.set_facecolor(style["bg_color"])
        ax = fig.add_subplot(111)
        ax.axis("off")
        ax.set_xlim(0, max(6, n * 1.2 + 1))
        ax.set_ylim(0, 4.5)
        ax.text(ax.get_xlim()[1] / 2, 4.2, title, fontsize=13,
                fontweight="bold", ha="center")
        _deco = ex.get("deco", "none")
        _dc = ex.get("deco_color", "#95a5a6")
        _xmax = ax.get_xlim()[1]
        if _deco == "frame":
            ax.add_patch(mpatches.Rectangle((0.1, 0.3), _xmax - 0.2, 3.9,
                                            fill=False, edgecolor=_dc, linewidth=1.5))
        elif _deco == "top_band":
            ax.add_patch(mpatches.Rectangle((0, 3.95), _xmax, 0.15,
                                            facecolor=_dc, alpha=0.35, edgecolor="none"))
        elif _deco == "corner_mark":
            ax.add_patch(mpatches.Rectangle((0.1, 3.95), 0.35, 0.3,
                                            facecolor=_dc, alpha=0.6, edgecolor="none"))
        elif _deco == "underline":
            ax.plot([1.5, _xmax - 1.5], [4.0, 4.0], color=_dc, linewidth=2.0)

        col_w = 1.0
        x0 = 1.0
        # Header row
        ax.text(x0 - 0.4, 3.2, "x:", fontsize=11 * fs_s, fontweight="bold")
        ax.text(x0 - 0.4, 2.4, "f(x):", fontsize=11 * fs_s, fontweight="bold")
        for i, (x, fx) in enumerate(examples):
            cx = x0 + i * col_w
            ax.add_patch(mpatches.Rectangle((cx - 0.4, 2.95), 0.8, 0.5,
                                            facecolor=style["palette"][i % len(style["palette"])],
                                            edgecolor="black", lw=1, alpha=0.7))
            ax.text(cx, 3.2, str(x), ha="center", va="center", fontsize=11 * fs_s,
                    fontweight="bold", color="white")
            ax.add_patch(mpatches.Rectangle((cx - 0.4, 2.15), 0.8, 0.5,
                                            facecolor=ex.get("output_bg", "#ecf0f1"),
                                            edgecolor="black", lw=1))
            ax.text(cx, 2.4, str(fx), ha="center", va="center", fontsize=11 * fs_s,
                    fontweight="bold", color="#2c3e50")
        # Test column
        cx = x0 + n * col_w + 0.4
        ax.add_patch(mpatches.Rectangle((cx - 0.4, 2.95), 0.8, 0.5,
                                        facecolor=ex.get("accent", "#e74c3c"),
                                        edgecolor="black", lw=1.4, alpha=0.85))
        ax.text(cx, 3.2, str(test_input), ha="center", va="center",
                fontsize=11 * fs_s, fontweight="bold", color="white")
        ax.add_patch(mpatches.Rectangle((cx - 0.4, 2.15), 0.8, 0.5,
                                        facecolor=ex.get("test_bg", "#fff8dc"),
                                        edgecolor=ex.get("accent", "#e74c3c"),
                                        lw=1.8, ls="--"))
        ax.text(cx, 2.4, "?", ha="center", va="center", fontsize=14 * fs_s,
                fontweight="bold", color=ex.get("accent", "#e74c3c"))
        if cfg.get("show_function_hint"):
            ax.text(ax.get_xlim()[1] / 2, 1.0, f"(hint: {rule_hint})",
                    fontsize=8, color="#95a5a6", ha="center")
        fig.tight_layout()
        return self.fig_to_pil(fig, dpi=style["dpi"])

    def _render_grid(self, examples, test_input, style, rng, title, cfg, rule_hint):
        sc = style["figsize_scale"]
        ex = style.get("_extra", {})
        fs_s = ex.get("fs_scale", 1.0)
        n = len(examples)
        cols = 3
        rows = (n + cols) // cols  # +1 for test
        fig = plt.figure(figsize=(8 * sc, max(4.5, rows * 1.5) * sc))
        fig.patch.set_facecolor(style["bg_color"])
        ax = fig.add_subplot(111)
        ax.set_xlim(0, cols * 2.4 + 0.5)
        ax.set_ylim(0, rows * 1.5 + 1.0)
        ax.axis("off")
        ax.text(ax.get_xlim()[1] / 2, ax.get_ylim()[1] - 0.3, title,
                fontsize=13, fontweight="bold", ha="center")
        _deco = ex.get("deco", "none")
        _dc = ex.get("deco_color", "#95a5a6")
        _xm, _ym = ax.get_xlim()[1], ax.get_ylim()[1]
        if _deco == "frame":
            ax.add_patch(mpatches.Rectangle((0.1, 0.2), _xm - 0.2, _ym - 0.4,
                                            fill=False, edgecolor=_dc, linewidth=1.5))
        elif _deco == "top_band":
            ax.add_patch(mpatches.Rectangle((0, _ym - 0.7), _xm, 0.2,
                                            facecolor=_dc, alpha=0.35, edgecolor="none"))
        elif _deco == "corner_mark":
            ax.add_patch(mpatches.Rectangle((0.1, _ym - 0.55), 0.35, 0.3,
                                            facecolor=_dc, alpha=0.6, edgecolor="none"))
        elif _deco == "underline":
            ax.plot([1.5, _xm - 1.5], [_ym - 0.65, _ym - 0.65],
                    color=_dc, linewidth=2.0)

        for i, (x, fx) in enumerate(examples):
            r = i // cols
            c = i % cols
            cx = c * 2.4 + 1.0
            cy = ax.get_ylim()[1] - 1.4 - r * 1.5
            color = style["palette"][i % len(style["palette"])]
            ax.add_patch(mpatches.FancyBboxPatch(
                (cx - 0.6, cy - 0.3), 0.7, 0.5,
                boxstyle="round,pad=0.04",
                fc=color, ec="black", lw=1, alpha=0.8))
            ax.text(cx - 0.25, cy - 0.05, str(x), ha="center", va="center",
                    fontsize=11 * fs_s, fontweight="bold", color="white")
            ax.annotate("", xy=(cx + 0.55, cy - 0.05), xytext=(cx + 0.15, cy - 0.05),
                        arrowprops=dict(arrowstyle="->",
                                        color=ex.get("arrow", "#7f8c8d"), lw=1.4))
            ax.add_patch(mpatches.FancyBboxPatch(
                (cx + 0.6, cy - 0.3), 0.7, 0.5,
                boxstyle="round,pad=0.04",
                fc=ex.get("output_bg", "#ecf0f1"), ec="black", lw=1))
            ax.text(cx + 0.95, cy - 0.05, str(fx), ha="center", va="center",
                    fontsize=11 * fs_s, fontweight="bold", color="#2c3e50")
        # test
        i = n
        r = i // cols
        c = i % cols
        cx = c * 2.4 + 1.0
        cy = ax.get_ylim()[1] - 1.4 - r * 1.5
        ax.add_patch(mpatches.FancyBboxPatch(
            (cx - 0.6, cy - 0.3), 0.7, 0.5,
            boxstyle="round,pad=0.04",
            fc=ex.get("accent", "#e74c3c"), ec="black", lw=1.2, alpha=0.85))
        ax.text(cx - 0.25, cy - 0.05, str(test_input), ha="center", va="center",
                fontsize=11 * fs_s, fontweight="bold", color="white")
        ax.annotate("", xy=(cx + 0.55, cy - 0.05), xytext=(cx + 0.15, cy - 0.05),
                    arrowprops=dict(arrowstyle="->",
                                    color=ex.get("arrow", "#7f8c8d"), lw=1.4))
        ax.add_patch(mpatches.FancyBboxPatch(
            (cx + 0.6, cy - 0.3), 0.7, 0.5,
            boxstyle="round,pad=0.04",
            fc=ex.get("test_bg", "#fff8dc"),
            ec=ex.get("accent", "#e74c3c"), lw=1.8, ls="--"))
        ax.text(cx + 0.95, cy - 0.05, "?", ha="center", va="center",
                fontsize=14 * fs_s, fontweight="bold",
                color=ex.get("accent", "#e74c3c"))
        if cfg.get("show_function_hint"):
            ax.text(ax.get_xlim()[1] / 2, 0.4, f"(hint: {rule_hint})",
                    fontsize=8, color="#95a5a6", ha="center")
        fig.tight_layout()
        return self.fig_to_pil(fig, dpi=style["dpi"])

if __name__ == "__main__":
    import os
    out_dir = "/tmp/env_check_taskc"
    os.makedirs(out_dir, exist_ok=True)
    env = InductiveRuleDiscoveryQA()
    for level in (0, 3, 6, 9):
        for seed in range(3):
            s = seed * 1000 + level * 37 + 17
            ok = env.generate(seed=s, parameter={"level": level})
            if not ok:
                print(f"[inductive_rule_discovery L{level} s{s}] FAILED")
                continue
            path = os.path.join(out_dir, f"inductive_rule_discovery_s{s}_L{level}.png")
            env.render().save(path)
            print(f"[inductive_rule_discovery L{level} s{s}] A={env._answer}")
