"""
Cattell-style IQ series-completion. A 1-row strip of N=3-6 frames evolves
under 2-3 simultaneous rules (motion + rotation + count + shading + size);
the model picks the next frame from 4 candidates labeled A-D.

Targets the inductive pattern-induction gap on IQ-test style benchmarks
(British 11+ / Cattell scale / Raven's). Each frame is a small box with
a couple of simple shapes inside (squares, circles, triangles, dots),
and rules combine over time:
  - motion: shape drifts position each step (NW, N, NE, E, SE, S, SW, W)
  - rotation: shape rotates 45/90 degrees per step
  - count: extra small marker added/removed each step
  - shading: shape toggles black/white each step

Distractors are generated by:
  - applying the wrong subset of rules (one rule violated)
  - off-by-one count
  - flipped shading
  - flipped motion direction
"""
import math
import random
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.transforms import Affine2D
from PIL import Image

from .standalone_base import StandaloneVisualEnv


_QUESTION_STEMS = [
    "Which of the boxes comes next in the sequence? Reply with the letter (A/B/C/D/E) in <answer>...</answer>.",
    "Identify the pattern in the sequence and choose the figure that comes next. Letter (A/B/C/D/E) in <answer>...</answer>.",
    "Examine the sequence of frames. Which option (A, B, C, D, or E) should come next? Letter in <answer>...</answer>.",
    "What choice (A, B, C, D, or E) should be in place of the question mark that fits the pattern? Letter in <answer>...</answer>.",
    "The sequence at the top follows a hidden rule. Which of the five options completes the sequence? Letter (A/B/C/D/E) in <answer>...</answer>.",
    "Identify the rule and choose the next figure in the sequence. Reply with one letter (A/B/C/D/E) in <answer>...</answer>.",
    "Which option from A-E should replace the question mark? Letter in <answer>...</answer>.",
    "Look at the sequence and determine the underlying rule(s). Which figure comes next? Letter (A/B/C/D/E) in <answer>...</answer>.",
    "Each frame in the sequence is produced from the previous by a consistent rule. Which option fits next? Letter (A/B/C/D/E) in <answer>...</answer>.",
    "Study the changes in the sequence. Which option should replace the question mark? Letter in <answer>...</answer>.",
    "Identify the pattern in the sequence and work out which one of the suggested images would complete the sequence. Letter (A/B/C/D/E) in <answer>...</answer>.",
    "Inspect the sequence carefully. Which of A-E fits as the next frame? Letter in <answer>...</answer>.",
    "Each step in the sequence applies the same rule(s). Which of the options is the next frame? Letter (A/B/C/D/E) in <answer>...</answer>.",
    "Determine the rule governing the sequence and pick the missing frame. Letter (A/B/C/D/E) in <answer>...</answer>.",
    "What comes next in the sequence? Choose A, B, C, D, or E. Letter in <answer>...</answer>.",
    "Study the pattern and choose the option that continues the series. Letter (A/B/C/D/E) in <answer>...</answer>.",
]


_SHAPES = ["square", "triangle", "circle", "diamond", "pentagon", "hexagon"]


def _shape_pts(shape, cx, cy, s):
    if shape == "circle":
        return None
    if shape == "square":
        return [(cx - s, cy - s), (cx + s, cy - s),
                (cx + s, cy + s), (cx - s, cy + s)]
    if shape == "triangle":
        return [(cx, cy + s), (cx - s, cy - s * 0.85),
                (cx + s, cy - s * 0.85)]
    if shape == "diamond":
        return [(cx, cy + s), (cx + s, cy),
                (cx, cy - s), (cx - s, cy)]
    if shape == "pentagon":
        return [(cx + s * math.cos(math.radians(72 * i + 90)),
                 cy + s * math.sin(math.radians(72 * i + 90)))
                for i in range(5)]
    if shape == "hexagon":
        return [(cx + s * math.cos(math.radians(60 * i + 30)),
                 cy + s * math.sin(math.radians(60 * i + 30)))
                for i in range(6)]
    return None


def _motion_delta(direction):
    d = {
        "N": (0, 1), "NE": (1, 1), "E": (1, 0), "SE": (1, -1),
        "S": (0, -1), "SW": (-1, -1), "W": (-1, 0), "NW": (-1, 1),
    }
    return d.get(direction, (0, 0))


class IQSeriesMixedRulesQA(StandaloneVisualEnv):
    ENV_NAME = "iq_series_mixed_rules"

    def _level_config(self, level: int) -> Dict:
        level = max(0, min(level, 9))
        if level <= 1:
            return {"n_seq": 3, "n_rules": 1, "rule_pool": ["rotate"], "rot_step": 90}
        if level <= 3:
            return {"n_seq": 4, "n_rules": 1, "rule_pool": ["rotate", "count_inc", "shade_toggle"], "rot_step": 90}
        if level <= 5:
            return {"n_seq": 5, "n_rules": 2,
                    "rule_pool": ["rotate", "count_inc", "shade_toggle", "motion"],
                    "rot_step": 90}
        if level <= 7:
            return {"n_seq": 5, "n_rules": 2,
                    "rule_pool": ["rotate", "count_inc", "shade_toggle", "motion", "size_inc"],
                    "rot_step": 45}
        return {"n_seq": 6, "n_rules": 3,
                "rule_pool": ["rotate", "count_inc", "shade_toggle", "motion", "size_inc"],
                "rot_step": 45}

    def _generate_problem(
        self, seed: int, parameter: Dict
    ) -> Optional[Tuple[str, str, Image.Image]]:
        level = int(parameter.get("level", 0))
        cfg = self._level_config(level)
        rng = random.Random((self.seed or 0) * 1019 + level * 53 + 401)

        for _ in range(40):
            r = self._try_generate(rng, cfg, level)
            if r is not None:
                return r
        return None

    def _try_generate(self, rng, cfg, level):
        # Pick rules
        rules = rng.sample(cfg["rule_pool"], min(cfg["n_rules"], len(cfg["rule_pool"])))
        rot_step = cfg["rot_step"]

        # Initial state
        state = {
            "shape": rng.choice(_SHAPES),
            "count": rng.choice([1, 2]),
            "rot_deg": 0,
            "shaded": rng.choice([True, False]),
            "pos": [0, 0],  # offset within frame in -1..1
            "size": 0.16,
            "motion_dir": rng.choice(["E", "SE", "S", "SW", "W", "NE", "NW", "N"]),
        }

        def _apply(s, rules, rot_step):
            s = dict(s)
            for r in rules:
                if r == "rotate":
                    s["rot_deg"] = (s["rot_deg"] + rot_step) % 360
                elif r == "count_inc":
                    if s["count"] >= 4 or rng.random() < 0.0:
                        s["count"] = max(1, s["count"] - 1)
                    else:
                        s["count"] = s["count"] + 1
                elif r == "shade_toggle":
                    s["shaded"] = not s["shaded"]
                elif r == "motion":
                    dx, dy = _motion_delta(s["motion_dir"])
                    nx = s["pos"][0] + dx * 0.30
                    ny = s["pos"][1] + dy * 0.30
                    # Bounce off edges
                    if abs(nx) > 0.6:
                        s["motion_dir"] = "W" if s["motion_dir"] == "E" else (
                            "E" if s["motion_dir"] == "W" else s["motion_dir"])
                        nx = max(-0.6, min(0.6, nx))
                    if abs(ny) > 0.6:
                        s["motion_dir"] = "S" if s["motion_dir"] == "N" else (
                            "N" if s["motion_dir"] == "S" else s["motion_dir"])
                        ny = max(-0.6, min(0.6, ny))
                    s["pos"] = [nx, ny]
                elif r == "size_inc":
                    s["size"] = min(0.22, s["size"] + 0.025)
            return s

        seq = [state]
        for _ in range(cfg["n_seq"] - 1):
            seq.append(_apply(seq[-1], rules, rot_step))
        correct = _apply(seq[-1], rules, rot_step)

        # Build distractors
        all_rules_pool = cfg["rule_pool"]
        unused = [r for r in all_rules_pool if r not in rules]
        distractors = []

        # 1) Apply wrong rule subset (one missing)
        if len(rules) > 1:
            partial = list(rules)
            partial.pop(0)
            distractors.append(_apply(seq[-1], partial, rot_step))
        # 2) Apply unused rule instead
        if unused:
            distractors.append(_apply(seq[-1], [unused[0]] + rules[1:], rot_step))
        # 3) Off-by-one count
        d = dict(correct)
        d["count"] = max(1, d["count"] + rng.choice([-1, 1]))
        distractors.append(d)
        # 4) Flipped shading
        d = dict(correct)
        d["shaded"] = not d["shaded"]
        distractors.append(d)
        # 5) Reversed rotation
        if "rotate" in rules:
            d = dict(correct)
            d["rot_deg"] = (seq[-1]["rot_deg"] - rot_step) % 360
            distractors.append(d)
        # 6) Extra step: apply the rules twice
        distractors.append(_apply(correct, rules, rot_step))
        # 7) Stay (no-op)
        distractors.append(dict(seq[-1]))
        # 8) Shape-swap distractor
        d = dict(correct)
        cur_idx = _SHAPES.index(d["shape"])
        d["shape"] = _SHAPES[(cur_idx + 1) % len(_SHAPES)]
        distractors.append(d)

        # Symmetry: rotations equivalent under shape's rotational symmetry
        # produce visually identical shapes; collapse them in the dedupe key
        # so we never hand the model two MCQ options that look the same.
        _SYM_FOLD = {
            "circle": 360,    # any rotation looks identical
            "square": 90,
            "diamond": 90,
            "triangle": 120,
            "pentagon": 72,
            "hexagon": 60,
        }
        def _key(c):
            fold = _SYM_FOLD.get(c["shape"], 360)
            eff_rot = int(c["rot_deg"]) % fold if fold < 360 else 0
            return (c["shape"], c["count"], eff_rot,
                    bool(c["shaded"]),
                    round(c["pos"][0], 2), round(c["pos"][1], 2),
                    round(c["size"], 2))

        seen = {_key(correct)}
        opts = [correct]
        for d in distractors:
            k = _key(d)
            if k not in seen:
                seen.add(k)
                opts.append(d)
            if len(opts) == 5:
                break
        # Top up if we don't have 5 yet (LogicVista sequence pattern uses A-E)
        tries = 0
        while len(opts) < 5 and tries < 60:
            tries += 1
            d = dict(correct)
            d["count"] = max(1, d["count"] + rng.choice([-2, -1, 1, 2]))
            d["shaded"] = not d["shaded"] if rng.random() < 0.5 else d["shaded"]
            if rng.random() < 0.5:
                d["rot_deg"] = (d["rot_deg"] + rng.choice([rot_step, -rot_step])) % 360
            k = _key(d)
            if k not in seen:
                seen.add(k)
                opts.append(d)
        if len(opts) < 5:
            return None

        opts = opts[:5]
        rng.shuffle(opts)
        ans_idx = opts.index(correct)
        answer = chr(ord("A") + ans_idx)

        q = rng.choice(_QUESTION_STEMS)
        if level <= 1:
            q = q + (
                " Hint: examine the sequence to find the rule (e.g., the shape "
                "rotates by a fixed angle each step, or the count of dots increases "
                "each step). Apply the same rule once more to find the next frame."
            )
        elif level <= 4:
            q = q + " Hint: identify the rule(s) and apply them once more. Be concise."

        img = self._render(seq, opts, rng)
        return q, answer, img

    # -------------------- rendering -------------------- #
    def _draw_state(self, ax, cx, cy, s, palette, rng):
        n = s["count"]
        size = s["size"]
        shape = s["shape"]
        rot_deg = s["rot_deg"]
        shaded = s["shaded"]
        # Apply position offset within the cell
        ox, oy = s["pos"]
        for k in range(n):
            kk = (k - (n - 1) / 2.0)
            sx = cx + ox + kk * size * 1.4
            sy = cy + oy
            color = "#212121" if shaded else "#ffffff"
            edge = "#212121"
            pts = _shape_pts(shape, sx, sy, size)
            if pts is None:
                patch = mpatches.Circle((sx, sy), size,
                                         facecolor=color, edgecolor=edge, linewidth=1.2)
            else:
                patch = mpatches.Polygon(pts, closed=True, facecolor=color,
                                          edgecolor=edge, linewidth=1.2)
            if rot_deg:
                patch.set_transform(
                    Affine2D().rotate_deg_around(sx, sy, rot_deg) + ax.transData)
            ax.add_patch(patch)

    def _render(self, seq, opts, rng) -> Image.Image:
        n_seq = len(seq)
        cell = 1.4
        fig = plt.figure(figsize=(2 + 1.5 * (n_seq + 1), 5.5))
        fig.patch.set_facecolor("#ffffff")
        # Two axes: top = sequence, bottom = options.
        ax_top = fig.add_subplot(2, 1, 1)
        ax_bot = fig.add_subplot(2, 1, 2)
        ax_top.set_facecolor("#ffffff")
        ax_bot.set_facecolor("#ffffff")
        ax_top.set_aspect("equal"); ax_bot.set_aspect("equal")
        ax_top.axis("off"); ax_bot.axis("off")

        # Sequence cells
        positions = [(i * cell, 0) for i in range(n_seq + 1)]
        for i, (state, (px, py)) in enumerate(zip(seq, positions[:n_seq])):
            rect = mpatches.Rectangle(
                (px - cell / 2 + 0.05, py - cell / 2 + 0.05),
                cell - 0.1, cell - 0.1,
                facecolor="#ffffff", edgecolor="#7f8c8d", linewidth=1)
            ax_top.add_patch(rect)
            self._draw_state(ax_top, px, py, state, [], rng)
            ax_top.text(px, py - cell / 2 - 0.18, f"{i + 1}",
                        fontsize=10, ha="center", va="top")
        # Question-mark cell
        qx, qy = positions[n_seq]
        rect = mpatches.Rectangle(
            (qx - cell / 2 + 0.05, qy - cell / 2 + 0.05),
            cell - 0.1, cell - 0.1,
            facecolor="#ffeaa7", edgecolor="#c0392b", linewidth=1.5)
        ax_top.add_patch(rect)
        ax_top.text(qx, qy, "?", fontsize=22, fontweight="bold",
                    ha="center", va="center", color="#c0392b")
        xs_all = [p[0] for p in positions]
        ax_top.set_xlim(min(xs_all) - 1.0, max(xs_all) + 1.0)
        ax_top.set_ylim(-cell, cell)

        # Options
        for i, opt in enumerate(opts):
            ox = i * cell
            oy = 0
            rect = mpatches.Rectangle(
                (ox - cell / 2 + 0.05, oy - cell / 2 + 0.05),
                cell - 0.1, cell - 0.1,
                facecolor="#ffffff", edgecolor="#34495e", linewidth=1)
            ax_bot.add_patch(rect)
            self._draw_state(ax_bot, ox, oy, opt, [], rng)
            ax_bot.text(ox, oy - cell / 2 - 0.18, f"({chr(ord('A') + i)})",
                        fontsize=12, fontweight="bold",
                        ha="center", va="top")
        ax_bot.set_xlim(-1.0, (len(opts) - 1) * cell + 1.0)
        ax_bot.set_ylim(-cell, cell)

        fig.subplots_adjust(left=0.02, right=0.98, top=0.95, bottom=0.05, hspace=0.35)
        return self.fig_to_pil(fig, dpi=120)


if __name__ == "__main__":
    import os
    out_dir = "/tmp/env_check_iq_series"
    os.makedirs(out_dir, exist_ok=True)
    env = IQSeriesMixedRulesQA()
    for level in (0, 3, 6, 9):
        for seed in range(3):
            ok = env.generate(seed=seed * 17 + 1, parameter={"level": level})
            if not ok:
                print(f"L{level} s{seed}: FAILED")
                continue
            env.render().save(os.path.join(out_dir, f"L{level}_s{seed}.png"))
            v = env.verify(f"<answer>{env._answer}</answer>")
            print(f"L{level} s{seed}: ans={env._answer} verify={v['accuracy']}")
