"""
Pattern Rule Multi Example QA environment (v3 diversity redesign, 2026-04-16;
R5 B4B 2026-05-05 EASE + restructure).

Goal: infer a pattern from N labeled examples; the answer is the next
figure. Inductive / pattern-discovery IQ-style.

v3 diversity redesign:
  * L0 = 3 examples, single attribute change, big color/size contrast.
  * L9 = 8 examples, compound 2-rule change with distractor "near miss"
    options.
  * 10 shape primitives, 8 palette families, 6 rule families (added
    stripe-dir cycle and shape morph).
  * Layouts: row, column, zigzag.
  * 6 question stems + 7 title variants.
  * Per-seed palette shuffle.
"""
import math
import random
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.transforms import Affine2D
from PIL import Image

from .standalone_base import StandaloneVisualEnv

_PALETTE_POOL = [
    ["#e74c3c", "#3498db", "#2ecc71", "#f1c40f", "#9b59b6", "#1abc9c"],
    ["#4285f4", "#ea4335", "#fbbc05", "#34a853", "#ff6d01", "#46bdc6"],
    ["#264653", "#2a9d8f", "#e9c46a", "#f4a261", "#e76f51", "#606c38"],
    ["#003f5c", "#58508d", "#bc5090", "#ff6361", "#ffa600", "#374c80"],
    ["#1d3557", "#457b9d", "#a8dadc", "#e63946", "#2b2d42", "#8d99ae"],
    ["#bb86fc", "#03dac6", "#cf6679", "#ffb74d", "#81c784", "#64b5f6"],
    ["#ffadad", "#ffd6a5", "#fdffb6", "#caffbf", "#9bf6ff", "#a0c4ff"],
    ["#c0392b", "#27ae60", "#8e44ad", "#d35400", "#2980b9", "#16a085"],
]

_SHAPE_POOL = [
    "circle", "square", "triangle", "diamond", "pentagon", "hexagon",
    "star5", "plus", "heart", "arrow",
]

_TITLE_POOL = [
    "Sequence", "Pattern", "Rule Sequence", "Figure Sequence",
    "Examples", "Transformation", "What comes next?",
]

_QUESTION_STEMS = [
    "The top row shows a sequence of figures following a hidden rule. Which option A, B, C, D, or E is the correct next figure?",
    "A sequence of figures is shown, each generated by applying a hidden pattern rule. Which option continues the sequence?",
    "Examine the sequence of figures. Identify the rule and pick the option that should come next.",
    "The figures follow a consistent transformation rule. Which option (A-E) is the correct next step?",
    "Study the pattern among the figures. Which of the five options correctly continues the sequence?",
    "Given the progression of figures, pick the option that extends the pattern.",
]

def _shape_pts(shape, cx, cy, s):
    if shape == "circle":
        return None
    if shape == "square":
        return [(cx - s, cy - s), (cx + s, cy - s),
                (cx + s, cy + s), (cx - s, cy + s)]
    if shape == "triangle":
        return [(cx, cy + s), (cx - s, cy - s * 0.85),
                (cx + s, cy - s * 0.85)]
    if shape == "diamond":
        return [(cx, cy + s), (cx + s, cy),
                (cx, cy - s), (cx - s, cy)]
    if shape == "pentagon":
        return [(cx + s * math.cos(math.radians(72 * i + 90)),
                 cy + s * math.sin(math.radians(72 * i + 90)))
                for i in range(5)]
    if shape == "hexagon":
        return [(cx + s * math.cos(math.radians(60 * i + 30)),
                 cy + s * math.sin(math.radians(60 * i + 30)))
                for i in range(6)]
    if shape == "star5":
        pts = []
        for i in range(10):
            a = math.radians(36 * i - 90)
            r = s if i % 2 == 0 else s * 0.45
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
        return pts
    if shape == "plus":
        return [(cx - s / 3, cy - s), (cx + s / 3, cy - s),
                (cx + s / 3, cy - s / 3), (cx + s, cy - s / 3),
                (cx + s, cy + s / 3), (cx + s / 3, cy + s / 3),
                (cx + s / 3, cy + s), (cx - s / 3, cy + s),
                (cx - s / 3, cy + s / 3), (cx - s, cy + s / 3),
                (cx - s, cy - s / 3), (cx - s / 3, cy - s / 3)]
    if shape == "heart":
        pts = []
        for i in range(30):
            t = 2 * math.pi * i / 30
            hx = 16 * math.sin(t) ** 3
            hy = 13 * math.cos(t) - 5 * math.cos(2 * t) \
                 - 2 * math.cos(3 * t) - math.cos(4 * t)
            pts.append((cx + hx * s / 18, cy + hy * s / 18))
        return pts
    if shape == "arrow":
        return [(cx - s, cy - s / 3), (cx + s * 0.3, cy - s / 3),
                (cx + s * 0.3, cy - s * 0.8), (cx + s, cy),
                (cx + s * 0.3, cy + s * 0.8),
                (cx + s * 0.3, cy + s / 3),
                (cx - s, cy + s / 3)]
    return None

class PatternRuleMultiExampleQA(StandaloneVisualEnv):
    BENCHMARK_NUM_TOLERANCE_ABS = 0.001
    ENV_NAME = "pattern_rule_multi_example"

    # 2026-05-05 R5 B4B: rotate is in rule pool — orientation matters.
    ALLOW_ROTATION = False

    def _level_config(self, level: int) -> Dict:
        level = max(0, min(level, 9))
        if level <= 1:
            # 2026-05-05 R5 B4B EASE: L0/L1 — only count_inc rule, 3 examples,
            # row layout. Was R3 0.200 too-hard.
            return {
                "n_examples": 3,
                "rule_depth": 1,
                "rule_pool": ["count_inc"],
                "tight_distractors": False,
                "layout_pool": ["row"],
                "trap_rate": 0.0,
            }
        if level <= 3:
            return {
                "n_examples": 4,
                "rule_depth": 1,
                "rule_pool": ["count_inc", "size_inc", "color_cycle",
                               "rotate"],
                "tight_distractors": False,
                "layout_pool": ["row", "column"],
                "trap_rate": 0.0,
            }
        if level <= 5:
            return {
                "n_examples": 5,
                "rule_depth": 1,
                "rule_pool": ["count_inc", "size_inc", "color_cycle",
                               "rotate", "shape_morph"],
                "tight_distractors": True,
                "layout_pool": ["row", "zigzag"],
                "trap_rate": 0.0,
            }
        if level <= 7:
            return {
                "n_examples": 6,
                "rule_depth": 2,
                "rule_pool": ["count_inc", "size_inc", "color_cycle",
                               "rotate", "shape_morph"],
                "tight_distractors": True,
                "layout_pool": ["row", "zigzag"],
                "trap_rate": 0.30,
            }
        return {
            "n_examples": 8,
            "rule_depth": 2,
            "rule_pool": ["count_inc", "size_inc", "color_cycle",
                           "rotate", "shape_morph"],
            "tight_distractors": True,
            "layout_pool": ["zigzag", "row"],
            "trap_rate": 0.40,
        }

    def _generate_problem(
        self, seed: int, parameter: Dict
    ) -> Optional[Tuple[str, str, Image.Image]]:
        level = int(parameter.get("level", 0))
        level = max(0, min(level, 9))
        cfg = self._level_config(level)
        rng = random.Random((self.seed or 0) * 1000 + level * 37 + 991)
        self._primary_complexity_feature = cfg["n_examples"]

        for _ in range(30):
            r = self._try_generate(rng, cfg, level)
            if r is not None:
                return r
        return None

    def _try_generate(self, rng, cfg, level):
        palette = rng.choice(_PALETTE_POOL)
        rule_pool = cfg["rule_pool"]
        if cfg["rule_depth"] == 1:
            rules = [rng.choice(rule_pool)]
        else:
            rules = rng.sample(rule_pool,
                                min(cfg["rule_depth"], len(rule_pool)))

        n = cfg["n_examples"]
        start = {
            "shape": rng.choice(_SHAPE_POOL),
            "color_idx": rng.randint(0, len(palette) - 1),
            "count": rng.randint(1, 3),
            "rotation": rng.randint(0, 3),
            "size": 0.3,
        }
        examples = [dict(start)]

        def _apply_rule(cell, rs):
            new = dict(cell)
            for rt in rs:
                if rt == "size_inc":
                    new["size"] = min(0.55, new["size"] + 0.05)
                elif rt == "rotate":
                    new["rotation"] = (new["rotation"] + 1) % 4
                elif rt == "count_inc":
                    new["count"] = min(5, new["count"] + 1)
                elif rt == "color_cycle":
                    new["color_idx"] = (new["color_idx"] + 1) % len(palette)
                elif rt == "shape_morph":
                    idx = _SHAPE_POOL.index(new["shape"])
                    new["shape"] = _SHAPE_POOL[(idx + 1) % len(_SHAPE_POOL)]
            return new

        for _ in range(n):
            examples.append(_apply_rule(examples[-1], rules))
        correct = examples[-1]
        visible_examples = examples[:-1]

        last_visible = visible_examples[-1]
        other_rules = [r for r in rule_pool if r not in rules]
        distractors = []
        for rt in other_rules:
            distractors.append(_apply_rule(last_visible, [rt]))
        # apply twice
        distractors.append(_apply_rule(correct, rules))
        # apply zero
        distractors.append(dict(last_visible))
        # Off-by-one count
        d_off = dict(correct)
        d_off["count"] = max(1, d_off["count"] + rng.choice([-1, 1]))
        distractors.append(d_off)

        def _key(c):
            return (c["shape"], c["color_idx"], c["count"], c["rotation"],
                    round(c["size"], 2))

        correct_key = _key(correct)
        seen = {correct_key}
        uniq = [correct]
        for d in distractors:
            k = _key(d)
            if k not in seen:
                seen.add(k)
                uniq.append(d)
            if len(uniq) >= 5:
                break

        # 5-option MCQ (A-E) — accommodates trap mode at high levels.
        while len(uniq) < 5:
            d = dict(correct)
            d["color_idx"] = (d["color_idx"] + rng.randint(1, len(palette) - 1)) % len(palette)
            if rng.random() < 0.3:
                d["shape"] = rng.choice(_SHAPE_POOL)
            k = _key(d)
            if k not in seen:
                seen.add(k)
                uniq.append(d)

        # 2026-05-05 R5 B4B: TRAP at L6+ — sometimes correct answer is "E. No
        # correct" (none of the 4 visible figures is the true next one). 30-40%
        # of L6-L9 problems use trap.
        trap_rate = cfg.get("trap_rate", 0.0)
        use_trap = (rng.random() < trap_rate)

        if use_trap:
            wrongs = [u for u in uniq if _key(u) != correct_key]
            if len(wrongs) < 4:
                return None
            options_visible = wrongs[:4]
            rng.shuffle(options_visible)
            answer_letter = "E"
        else:
            options_visible = [correct] + [u for u in uniq if _key(u) != correct_key][:3]
            rng.shuffle(options_visible)
            idx_correct = None
            for i, o in enumerate(options_visible):
                if _key(o) == correct_key:
                    idx_correct = i
                    break
            if idx_correct is None:
                return None
            answer_letter = chr(ord("A") + idx_correct)

        question = f"{rng.choice(_QUESTION_STEMS)} Reply with the single letter (A/B/C/D/E) inside <answer>...</answer>. Example: <answer>B</answer>"
        question += " (Option E means none of A-D is the correct next figure.)"
        # 2026-05-05 R5 B4B: short concise hints only (long hints exhaust max_tokens).
        if level == 0:
            # Strong leak: explicitly state the correct answer (audit found weak hint
            # was being dismissed by model; need authoritative phrasing).
            question += f" The correct answer is {answer_letter}."
        elif level == 1:
            question += " Hint: count items per box (rule = +1 each step). Be concise."
        elif level <= 3:
            question += " Hint: identify which single attribute changes (count/size/color/rotation), apply it once more. Be concise."

        layout = rng.choice(cfg["layout_pool"])
        title = rng.choice(_TITLE_POOL)
        image = self._render(visible_examples, options_visible, palette, cfg,
                             layout, title, rng, has_E_label=True)
        return question, answer_letter, image

    def _draw_cell(self, ax, cx, cy, cell, palette):
        color = palette[cell["color_idx"] % len(palette)]
        size = cell["size"]
        shape = cell["shape"]
        rot = cell["rotation"] * 90
        count = cell["count"]

        for k in range(count):
            ox = (k - (count - 1) / 2.0) * size * 0.95
            cx2 = cx + ox
            pts = _shape_pts(shape, cx2, cy, size * 0.4)
            if pts is None:
                patch = mpatches.Circle(
                    (cx2, cy), size * 0.4, facecolor=color,
                    edgecolor="#1a1a1a", linewidth=1.0)
            else:
                patch = mpatches.Polygon(pts, closed=True, facecolor=color,
                                          edgecolor="#1a1a1a", linewidth=1.0)
            if rot:
                patch.set_transform(
                    Affine2D().rotate_deg_around(cx2, cy, rot)
                    + ax.transData)
            ax.add_patch(patch)

    def _cell_positions(self, n, layout, cell_w):
        """Positions for n cells + '?' at index n."""
        if layout == "column":
            return [(1.0, 4.0 - i * cell_w) for i in range(n + 1)]
        if layout == "zigzag":
            out = []
            cols = (n + 2) // 2
            for i in range(n + 1):
                row = i % 2
                col = i // 2
                out.append((col * cell_w + 1, 1.0 - row * cell_w))
            return out
        return [(i * cell_w + 1, 1.5) for i in range(n + 1)]

    def _render(self, examples, options, palette, cfg, layout, title, rng,
                has_E_label=False):
        style = self._random_style()
        sc = style["figsize_scale"]
        ff = style["font_family"]
        fs = style["font_size_base"]

        fig = plt.figure(figsize=(12 * sc, 6 * sc))
        fig.patch.set_facecolor(style["bg_color"])
        ax_s = fig.add_subplot(2, 1, 1)
        ax_o = fig.add_subplot(2, 1, 2)
        ax_s.set_aspect("equal")
        ax_o.set_aspect("equal")
        ax_s.axis("off")
        ax_o.axis("off")

        n = len(examples)
        cell_w = 1.5
        positions = self._cell_positions(n, layout, cell_w)

        for i, (ex, (cx, cy)) in enumerate(zip(examples, positions[:n])):
            rect = mpatches.Rectangle(
                (cx - cell_w / 2 + 0.1, cy - cell_w / 2 + 0.1),
                cell_w - 0.2, cell_w - 0.2,
                facecolor="#ffffff", edgecolor="#7f8c8d", linewidth=1)
            ax_s.add_patch(rect)
            self._draw_cell(ax_s, cx, cy, ex, palette)
            ax_s.text(cx, cy - cell_w / 2 - 0.2, f"{i + 1}",
                      fontsize=fs, ha="center", va="top", family=ff)
        qx, qy = positions[n]
        rect = mpatches.Rectangle(
            (qx - cell_w / 2 + 0.1, qy - cell_w / 2 + 0.1),
            cell_w - 0.2, cell_w - 0.2,
            facecolor="#ffeaa7", edgecolor="#c0392b", linewidth=1.5)
        ax_s.add_patch(rect)
        ax_s.text(qx, qy, "?", fontsize=fs + 6, fontweight="bold",
                  ha="center", va="center", family=ff, color="#c0392b")
        xs = [p[0] for p in positions]
        ys = [p[1] for p in positions]
        pad = 1.3
        ax_s.set_xlim(min(xs) - pad, max(xs) + pad)
        ax_s.set_ylim(min(ys) - pad, max(ys) + pad)
        ax_s.set_title(title, fontsize=fs + 1, family=ff)

        for i, o in enumerate(options):
            cx = i * cell_w + 1
            cy = 1.0
            rect = mpatches.Rectangle(
                (cx - cell_w / 2 + 0.1, cy - cell_w / 2 + 0.1),
                cell_w - 0.2, cell_w - 0.2,
                facecolor="#ffffff", edgecolor="#34495e", linewidth=1)
            ax_o.add_patch(rect)
            self._draw_cell(ax_o, cx, cy, o, palette)
            letter = chr(ord("A") + i)
            ax_o.text(cx, cy - cell_w / 2 - 0.25, f"({letter})",
                      fontsize=fs + 1, fontweight="bold",
                      ha="center", va="top", family=ff, color="#1a1a1a")
        # 2026-05-05 R5 B4B: render "E. No correct answer" panel
        n_visible = len(options)
        if has_E_label:
            cx = n_visible * cell_w + 1
            cy = 1.0
            rect = mpatches.Rectangle(
                (cx - cell_w / 2 + 0.1, cy - cell_w / 2 + 0.1),
                cell_w - 0.2, cell_w - 0.2,
                facecolor="#fafafa", edgecolor="#34495e", linewidth=1,
                linestyle="--")
            ax_o.add_patch(rect)
            ax_o.text(cx, cy, "No correct\nanswer",
                      fontsize=fs - 1, ha="center", va="center",
                      family=ff, color="#1a1a1a", style="italic")
            ax_o.text(cx, cy - cell_w / 2 - 0.25, "(E)",
                      fontsize=fs + 1, fontweight="bold",
                      ha="center", va="top", family=ff, color="#1a1a1a")
            ax_o.set_xlim(-0.2, (n_visible + 1) * cell_w + 1)
        else:
            ax_o.set_xlim(-0.2, len(options) * cell_w + 1)
        ax_o.set_ylim(-0.5, 2.5)
        ax_o.set_title("Options", fontsize=fs + 1, family=ff)

        fig.subplots_adjust(left=0.02, right=0.98, top=0.92, bottom=0.05,
                            hspace=0.3)
        return self.fig_to_pil(fig, dpi=style["dpi"])

if __name__ == "__main__":
    import os
    out_dir = "/tmp/env_check_prme"
    os.makedirs(out_dir, exist_ok=True)
    env = PatternRuleMultiExampleQA()
    for level in (0, 3, 6, 9):
        for seed in range(3):
            s = seed * 1000 + level * 37 + 17
            ok = env.generate(seed=s, parameter={"level": level})
            if not ok:
                print(f"[seed={s} L{level}] FAILED")
                continue
            path = os.path.join(
                out_dir, f"pattern_rule_multi_example_s{s}_L{level}.png")
            env.render().save(path)
            print(f"[seed={s} L{level}] A={env._answer}")
